# arm-linux-gnueabihf-gcc toolchain

if(NOT TOOLCHAIN_PREFIX)
	set(TOOLCHAIN_PREFIX aarch64-linux-gnu)
endif()

set(triple aarch64-linux-gnu)

set(CMAKE_LIBRARY_ARCHITECTURE ${triple})

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_SYSTEM_VERSION 1)

if(NOT CMAKE_C_COMPILER)
	set(CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
endif()
set(CMAKE_C_COMPILER_TARGET ${triple})

if(NOT CMAKE_CXX_COMPILER)
	set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
endif()
set(CMAKE_CXX_COMPILER_TARGET ${triple})

if(NOT CMAKE_ASM_COMPILER)
	set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
endif()

# compiler tools
if(NOT CMAKE_AR)
	find_program(CMAKE_AR ${TOOLCHAIN_PREFIX}-gcc-ar)
endif()
if(NOT CMAKE_GDB)
	find_program(CMAKE_GDB ${TOOLCHAIN_PREFIX}-gdb)
endif()
if(NOT CMAKE_LD)
	find_program(CMAKE_LD ${TOOLCHAIN_PREFIX}-ld)
endif()
if(NOT CMAKE_LINKER)
	find_program(CMAKE_LINKER ${TOOLCHAIN_PREFIX}-ld)
endif()
if(NOT CMAKE_NM)
	find_program(CMAKE_NM ${TOOLCHAIN_PREFIX}-gcc-nm)
endif()
if(NOT CMAKE_OBJCOPY)
	find_program(CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy)
endif()
if(NOT CMAKE_OBJDUMP)
	find_program(CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}-objdump)
endif()
if(NOT CMAKE_RANLIB)
	find_program(CMAKE_RANLIB ${TOOLCHAIN_PREFIX}-gcc-ranlib)
endif()
if(NOT CMAKE_STRIP)
	find_program(CMAKE_STRIP ${TOOLCHAIN_PREFIX}-strip)
endif()

set(CMAKE_FIND_ROOT_PATH get_file_component(${CMAKE_C_COMPILER} PATH))
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# os tools
foreach(tool grep make)
	string(TOUPPER ${tool} TOOL)
	find_program(${TOOL} ${tool})
	if(NOT ${TOOL})
		message(FATAL_ERROR "could not find ${tool}")
	endif()
endforeach()
